version: "3"

services:
  openvpn:
    image: ${IMAGE_NAME:-kylemanna/openvpn}:${IMAGE_TAG:-latest}
    build: .
    volumes:
      - type: bind
        source: ./config
        target: /etc/openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: always
